// Code generated by protoc-gen-go.
// source: sourcebackend.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SearchReply_Type int32

const (
	SearchReply_MATCH           SearchReply_Type = 0
	SearchReply_PROGRESS_UPDATE SearchReply_Type = 1
)

var SearchReply_Type_name = map[int32]string{
	0: "MATCH",
	1: "PROGRESS_UPDATE",
}
var SearchReply_Type_value = map[string]int32{
	"MATCH":           0,
	"PROGRESS_UPDATE": 1,
}

func (x SearchReply_Type) String() string {
	return proto1.EnumName(SearchReply_Type_name, int32(x))
}
func (SearchReply_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{5, 0} }

type FileRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *FileRequest) Reset()                    { *m = FileRequest{} }
func (m *FileRequest) String() string            { return proto1.CompactTextString(m) }
func (*FileRequest) ProtoMessage()               {}
func (*FileRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type FileReply struct {
	Contents []byte `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *FileReply) Reset()                    { *m = FileReply{} }
func (m *FileReply) String() string            { return proto1.CompactTextString(m) }
func (*FileReply) ProtoMessage()               {}
func (*FileReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type SearchRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	// Rewritten URL (after RewriteQuery()) with all the parameters that
	// are relevant for ranking.
	RewrittenUrl string `protobuf:"bytes,2,opt,name=rewritten_url,json=rewrittenUrl" json:"rewritten_url,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto1.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type Match struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Line uint32 `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	// Contents of line-2.
	Ctxp2 string `protobuf:"bytes,3,opt,name=ctxp2" json:"ctxp2,omitempty"`
	// Contents of line-1.
	Ctxp1 string `protobuf:"bytes,4,opt,name=ctxp1" json:"ctxp1,omitempty"`
	// Contents of the line containing the match.
	Context string `protobuf:"bytes,5,opt,name=context" json:"context,omitempty"`
	// Contents of line+1.
	Ctxn1 string `protobuf:"bytes,6,opt,name=ctxn1" json:"ctxn1,omitempty"`
	// Contents of line+2.
	Ctxn2    string  `protobuf:"bytes,7,opt,name=ctxn2" json:"ctxn2,omitempty"`
	Pathrank float32 `protobuf:"fixed32,8,opt,name=pathrank" json:"pathrank,omitempty"`
	Ranking  float32 `protobuf:"fixed32,9,opt,name=ranking" json:"ranking,omitempty"`
	Package  string  `protobuf:"bytes,10,opt,name=package" json:"package,omitempty"`
}

func (m *Match) Reset()                    { *m = Match{} }
func (m *Match) String() string            { return proto1.CompactTextString(m) }
func (*Match) ProtoMessage()               {}
func (*Match) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type ProgressUpdate struct {
	FilesProcessed uint64 `protobuf:"varint,1,opt,name=files_processed,json=filesProcessed" json:"files_processed,omitempty"`
	FilesTotal     uint64 `protobuf:"varint,2,opt,name=files_total,json=filesTotal" json:"files_total,omitempty"`
}

func (m *ProgressUpdate) Reset()                    { *m = ProgressUpdate{} }
func (m *ProgressUpdate) String() string            { return proto1.CompactTextString(m) }
func (*ProgressUpdate) ProtoMessage()               {}
func (*ProgressUpdate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type SearchReply struct {
	Type           SearchReply_Type `protobuf:"varint,1,opt,name=type,enum=proto.SearchReply_Type" json:"type,omitempty"`
	Match          *Match           `protobuf:"bytes,2,opt,name=match" json:"match,omitempty"`
	ProgressUpdate *ProgressUpdate  `protobuf:"bytes,3,opt,name=progress_update,json=progressUpdate" json:"progress_update,omitempty"`
}

func (m *SearchReply) Reset()                    { *m = SearchReply{} }
func (m *SearchReply) String() string            { return proto1.CompactTextString(m) }
func (*SearchReply) ProtoMessage()               {}
func (*SearchReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *SearchReply) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *SearchReply) GetProgressUpdate() *ProgressUpdate {
	if m != nil {
		return m.ProgressUpdate
	}
	return nil
}

func init() {
	proto1.RegisterType((*FileRequest)(nil), "proto.FileRequest")
	proto1.RegisterType((*FileReply)(nil), "proto.FileReply")
	proto1.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto1.RegisterType((*Match)(nil), "proto.Match")
	proto1.RegisterType((*ProgressUpdate)(nil), "proto.ProgressUpdate")
	proto1.RegisterType((*SearchReply)(nil), "proto.SearchReply")
	proto1.RegisterEnum("proto.SearchReply_Type", SearchReply_Type_name, SearchReply_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for SourceBackend service

type SourceBackendClient interface {
	// File reads the file and returns its contents.
	File(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error)
	// Search performs the given query and streams matches/progress updates.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (SourceBackend_SearchClient, error)
}

type sourceBackendClient struct {
	cc *grpc.ClientConn
}

func NewSourceBackendClient(cc *grpc.ClientConn) SourceBackendClient {
	return &sourceBackendClient{cc}
}

func (c *sourceBackendClient) File(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error) {
	out := new(FileReply)
	err := grpc.Invoke(ctx, "/proto.SourceBackend/File", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceBackendClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (SourceBackend_SearchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SourceBackend_serviceDesc.Streams[0], c.cc, "/proto.SourceBackend/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &sourceBackendSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SourceBackend_SearchClient interface {
	Recv() (*SearchReply, error)
	grpc.ClientStream
}

type sourceBackendSearchClient struct {
	grpc.ClientStream
}

func (x *sourceBackendSearchClient) Recv() (*SearchReply, error) {
	m := new(SearchReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SourceBackend service

type SourceBackendServer interface {
	// File reads the file and returns its contents.
	File(context.Context, *FileRequest) (*FileReply, error)
	// Search performs the given query and streams matches/progress updates.
	Search(*SearchRequest, SourceBackend_SearchServer) error
}

func RegisterSourceBackendServer(s *grpc.Server, srv SourceBackendServer) {
	s.RegisterService(&_SourceBackend_serviceDesc, srv)
}

func _SourceBackend_File_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SourceBackendServer).File(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _SourceBackend_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceBackendServer).Search(m, &sourceBackendSearchServer{stream})
}

type SourceBackend_SearchServer interface {
	Send(*SearchReply) error
	grpc.ServerStream
}

type sourceBackendSearchServer struct {
	grpc.ServerStream
}

func (x *sourceBackendSearchServer) Send(m *SearchReply) error {
	return x.ServerStream.SendMsg(m)
}

var _SourceBackend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SourceBackend",
	HandlerType: (*SourceBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "File",
			Handler:    _SourceBackend_File_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _SourceBackend_Search_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor1 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0x46, 0xda, 0xad, 0x37, 0xfd, 0xd2, 0xdd, 0x10, 0xd6, 0x5e, 0x00, 0x23, 0x31, 0x24,
	0xa4, 0x8a, 0x06, 0x89, 0x47, 0xa4, 0x01, 0x03, 0x84, 0x84, 0xa8, 0xdc, 0xf6, 0x85, 0x97, 0x2a,
	0x4b, 0x4d, 0x5b, 0x2d, 0x24, 0xc6, 0x71, 0xb5, 0xf5, 0x0f, 0xf2, 0x7f, 0xf8, 0x07, 0xd8, 0xd7,
	0x49, 0xb7, 0xc2, 0x9e, 0xec, 0x73, 0xee, 0xb1, 0xef, 0xc7, 0xb9, 0x70, 0x5c, 0x16, 0x1b, 0x9d,
	0xca, 0xcb, 0x24, 0xbd, 0x92, 0xf9, 0x62, 0xa8, 0x74, 0x61, 0x0a, 0x6c, 0xd2, 0xc1, 0x9f, 0x42,
	0xf4, 0x71, 0x9d, 0x49, 0x21, 0x7f, 0x6d, 0x64, 0x69, 0x10, 0x21, 0x54, 0x89, 0x59, 0xb1, 0xe0,
	0x49, 0xf0, 0xa2, 0x2d, 0xe8, 0xce, 0xcf, 0xa0, 0xed, 0x25, 0x2a, 0xdb, 0xe2, 0x29, 0x1c, 0xa5,
	0x45, 0x6e, 0x64, 0x6e, 0x4a, 0x12, 0x75, 0xc4, 0x0e, 0xf3, 0x2f, 0xd0, 0x9d, 0xc8, 0x44, 0xa7,
	0xab, 0xfa, 0xb7, 0x13, 0x68, 0xda, 0x8b, 0xde, 0x56, 0xdf, 0x79, 0x80, 0xcf, 0xa0, 0xab, 0xe5,
	0xb5, 0x5e, 0x1b, 0xfb, 0x6a, 0xbe, 0xd1, 0x19, 0x3b, 0xa0, 0x68, 0x67, 0x47, 0xce, 0x74, 0xc6,
	0xff, 0x04, 0xd0, 0xfc, 0x9a, 0x98, 0x74, 0x75, 0x5f, 0x49, 0x8e, 0xcb, 0xd6, 0xb9, 0xa4, 0x97,
	0x5d, 0x41, 0x77, 0x97, 0x2c, 0x35, 0x37, 0x2a, 0x66, 0x0f, 0x7c, 0x32, 0x02, 0x35, 0x3b, 0x62,
	0xe1, 0x2d, 0x3b, 0x42, 0x06, 0x87, 0x54, 0xf5, 0x8d, 0x61, 0x4d, 0xe2, 0x6b, 0x58, 0xe9, 0xf3,
	0x11, 0x6b, 0xed, 0xf4, 0xf9, 0xa8, 0x66, 0x63, 0x76, 0x78, 0xcb, 0xc6, 0x6e, 0x16, 0xae, 0x1a,
	0x9d, 0xe4, 0x57, 0xec, 0xc8, 0x06, 0x0e, 0xc4, 0x0e, 0xbb, 0x0c, 0xee, 0x5c, 0xe7, 0x4b, 0xd6,
	0xa6, 0x50, 0x0d, 0x5d, 0x44, 0x59, 0x27, 0x92, 0xa5, 0x64, 0xe0, 0x73, 0x57, 0x90, 0x7f, 0x87,
	0xde, 0x58, 0x17, 0x4b, 0x2d, 0xcb, 0x72, 0xa6, 0x16, 0x89, 0x91, 0x78, 0x06, 0xfd, 0x1f, 0x76,
	0xf4, 0xe5, 0xdc, 0x9a, 0x95, 0x5a, 0x5a, 0x2e, 0x68, 0x0c, 0xa1, 0xe8, 0x11, 0x3d, 0xae, 0x59,
	0x7c, 0x0c, 0x91, 0x17, 0x9a, 0xc2, 0x24, 0x7e, 0xa2, 0xa1, 0x00, 0xa2, 0xa6, 0x8e, 0xe1, 0xbf,
	0x03, 0x88, 0x6a, 0x73, 0x9c, 0x8f, 0x2f, 0x21, 0x34, 0x5b, 0x25, 0xe9, 0xbb, 0x5e, 0xfc, 0xc8,
	0x2f, 0xc5, 0xf0, 0x8e, 0x62, 0x38, 0xb5, 0x61, 0x41, 0x22, 0xe4, 0xd0, 0xfc, 0xe9, 0xbc, 0xa0,
	0x7f, 0xa3, 0xb8, 0x53, 0xa9, 0xc9, 0x1f, 0xe1, 0x43, 0xf8, 0x16, 0xfa, 0xaa, 0x2a, 0x7e, 0xbe,
	0xa1, 0xea, 0xc9, 0x88, 0x28, 0x7e, 0x58, 0xa9, 0xf7, 0x5b, 0x13, 0x3d, 0xb5, 0x87, 0xf9, 0x73,
	0x08, 0x5d, 0x46, 0x6c, 0x5b, 0xdf, 0xcf, 0xa7, 0xef, 0x3f, 0x0f, 0x1a, 0x78, 0x0c, 0xfd, 0xb1,
	0xf8, 0xf6, 0x49, 0x5c, 0x4c, 0x26, 0xf3, 0xd9, 0xf8, 0xc3, 0xf9, 0xf4, 0x62, 0x10, 0xc4, 0xd7,
	0x76, 0xc9, 0x68, 0x9d, 0xdf, 0xf9, 0x75, 0xc6, 0x21, 0x84, 0x6e, 0x3d, 0x11, 0xab, 0x3c, 0x77,
	0xd6, 0xf9, 0x74, 0xb0, 0xc7, 0xd9, 0xae, 0x78, 0x03, 0xdf, 0x40, 0xcb, 0xb7, 0x89, 0x27, 0xff,
	0x74, 0xed, 0xdf, 0xe0, 0xff, 0xb3, 0xe0, 0x8d, 0x57, 0xc1, 0x65, 0x8b, 0xe8, 0xd7, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x52, 0x9f, 0x87, 0x0d, 0x4e, 0x03, 0x00, 0x00,
}
