name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        # Latest stable version of Go, e.g. 1.26.6
        go-version: 'stable'

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Install Linux package dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends slimit yui-compressor zopfli

    - name: Go Vet
      run: |
        go vet

    - name: Build
      run: |
        go build -v ./cmd/...

    - name: Test
      run: |
        go test -v ./...

    - name: Test (SIMD)
      env:
        GOEXPERIMENT: simd
        GOAMD64: v3
      run: |
        go test -v ./...
